export const products = [
  {
    id: 1,
    product: 'I/O Topology',
    parent: 'GRAVITY',
    designLead: 'Design Lead',
    designTeam: 3,
    designGaps: 5,
    stakeholderMapHealth: 'STRONG',
    teamMaturity: 'ESTABLISHED',
    designDevTat: '12 days',
    tatTrend: 'down',
    customerInteraction: 'FRESH',
    experienceArchitectureMaturity: 4
  },
  {
    id: 2,
    product: 'ICIC',
    parent: 'GRAVITY',
    designLead: 'Design Lead',
    designTeam: 2,
    designGaps: 8,
    stakeholderMapHealth: 'MODERATE',
    teamMaturity: 'DEVELOPING',
    designDevTat: '18 days',
    tatTrend: 'up',
    customerInteraction: 'STALE',
    experienceArchitectureMaturity: 2
  },
  {
    id: 3,
    product: 'Provable Value',
    parent: 'RHEA',
    designLead: 'Design Lead',
    designTeam: 5,
    designGaps: 2,
    stakeholderMapHealth: 'STRONG',
    teamMaturity: 'LEADING',
    designDevTat: '8 days',
    tatTrend: 'down',
    customerInteraction: 'FRESH',
    experienceArchitectureMaturity: 5
  },
  {
    id: 4,
    product: 'Commercial Experience',
    parent: 'RHEA',
    designLead: 'Design Lead',
    designTeam: 4,
    designGaps: 12,
    stakeholderMapHealth: 'WEAK',
    teamMaturity: 'FOUNDATIONAL',
    designDevTat: '25 days',
    tatTrend: 'up',
    customerInteraction: 'STALE',
    experienceArchitectureMaturity: 1
  },
  {
    id: 5,
    product: 'Application Control Center',
    parent: 'RHEA',
    designLead: 'Design Lead',
    designTeam: 3,
    designGaps: 6,
    stakeholderMapHealth: 'MODERATE',
    teamMaturity: 'ESTABLISHED',
    designDevTat: '14 days',
    tatTrend: 'down',
    customerInteraction: 'FRESH',
    experienceArchitectureMaturity: 3
  },
  {
    id: 6,
    product: 'IBM Z Next',
    parent: 'RHEA',
    designLead: 'Design Lead',
    designTeam: 5,
    designGaps: 3,
    stakeholderMapHealth: 'STRONG',
    teamMaturity: 'ADVANCED',
    designDevTat: '10 days',
    tatTrend: 'down',
    customerInteraction: 'FRESH',
    experienceArchitectureMaturity: 4
  },
  {
    id: 7,
    product: 'IBM LinuxONE Next',
    parent: 'RHEA',
    designLead: 'Design Lead',
    designTeam: 4,
    designGaps: 4,
    stakeholderMapHealth: 'STRONG',
    teamMaturity: 'ADVANCED',
    designDevTat: '11 days',
    tatTrend: 'down',
    customerInteraction: 'FRESH',
    experienceArchitectureMaturity: 4
  },
  {
    id: 8,
    product: 'Infrastructure Foundation',
    parent: 'RHEA/DEMETER',
    designLead: 'Design Lead',
    designTeam: 2,
    designGaps: 9,
    stakeholderMapHealth: 'MODERATE',
    teamMaturity: 'DEVELOPING',
    designDevTat: '20 days',
    tatTrend: 'up',
    customerInteraction: 'STALE',
    experienceArchitectureMaturity: 2
  },
  {
    id: 9,
    product: 'Crypto-Simplification',
    parent: 'SECURITY',
    designLead: 'Design Lead',
    designTeam: 3,
    designGaps: 7,
    stakeholderMapHealth: 'MODERATE',
    teamMaturity: 'ESTABLISHED',
    designDevTat: '15 days',
    tatTrend: 'down',
    customerInteraction: 'FRESH',
    experienceArchitectureMaturity: 3
  },
  {
    id: 10,
    product: 'Crypto-Inventory and Discovery',
    parent: 'SECURITY',
    designLead: 'Design Lead',
    designTeam: 2,
    designGaps: 10,
    stakeholderMapHealth: 'WEAK',
    teamMaturity: 'DEVELOPING',
    designDevTat: '22 days',
    tatTrend: 'up',
    customerInteraction: 'STALE',
    experienceArchitectureMaturity: 2
  },
  {
    id: 11,
    product: 'Haven',
    parent: 'SECURITY',
    designLead: 'Design Lead',
    designTeam: 1,
    designGaps: 15,
    stakeholderMapHealth: 'WEAK',
    teamMaturity: 'FOUNDATIONAL',
    designDevTat: '30 days',
    tatTrend: 'up',
    customerInteraction: 'STALE',
    experienceArchitectureMaturity: 0
  },
  {
    id: 12,
    product: 'Regulated Digital Assets',
    parent: 'SECURITY',
    designLead: 'Design Lead',
    designTeam: 4,
    designGaps: 4,
    stakeholderMapHealth: 'STRONG',
    teamMaturity: 'ESTABLISHED',
    designDevTat: '13 days',
    tatTrend: 'down',
    customerInteraction: 'FRESH',
    experienceArchitectureMaturity: 4
  },
  {
    id: 13,
    product: 'Confidential Computing',
    parent: 'SECURITY',
    designLead: 'Design Lead',
    designTeam: 5,
    designGaps: 2,
    stakeholderMapHealth: 'STRONG',
    teamMaturity: 'LEADING',
    designDevTat: '9 days',
    tatTrend: 'down',
    customerInteraction: 'FRESH',
    experienceArchitectureMaturity: 5
  },
  {
    id: 14,
    product: 'Gekko',
    parent: 'NZLI',
    designLead: 'Design Lead',
    designTeam: 2,
    designGaps: 14,
    stakeholderMapHealth: 'WEAK',
    teamMaturity: 'FOUNDATIONAL',
    designDevTat: '28 days',
    tatTrend: 'up',
    customerInteraction: 'STALE',
    experienceArchitectureMaturity: 1
  },
  {
    id: 15,
    product: 'Content Overhaul',
    parent: 'NZLI',
    designLead: 'Design Lead',
    designTeam: 4,
    designGaps: 1,
    stakeholderMapHealth: 'STRONG',
    teamMaturity: 'LEADING',
    designDevTat: '7 days',
    tatTrend: 'down',
    customerInteraction: 'FRESH',
    experienceArchitectureMaturity: 5
  },
  {
    id: 16,
    product: 'AI Assistant',
    parent: 'NZLI',
    designLead: 'Design Lead',
    designTeam: 3,
    designGaps: 6,
    stakeholderMapHealth: 'MODERATE',
    teamMaturity: 'ESTABLISHED',
    designDevTat: '16 days',
    tatTrend: 'down',
    customerInteraction: 'FRESH',
    experienceArchitectureMaturity: 3
  },
  {
    id: 17,
    product: 'Demo Portal',
    parent: 'NZLI',
    designLead: 'Design Lead',
    designTeam: 2,
    designGaps: 8,
    stakeholderMapHealth: 'MODERATE',
    teamMaturity: 'DEVELOPING',
    designDevTat: '19 days',
    tatTrend: 'up',
    customerInteraction: 'STALE',
    experienceArchitectureMaturity: 2
  },
  {
    id: 18,
    product: 'Digital Sovereig nty',
    parent: 'L1',
    designLead: 'Design Lead',
    designTeam: 3,
    designGaps: 7,
    stakeholderMapHealth: 'MODERATE',
    teamMaturity: 'ESTABLISHED',
    designDevTat: '17 days',
    tatTrend: 'down',
    customerInteraction: 'FRESH',
    experienceArchitectureMaturity: 3
  }
];

export const summaryData = {
  totalProducts: 18,
  rhea: 7,
  undocumentedMarkers: 8
};

// Made with Bob
